name: fluetooth_example
description: Demonstrates how to use the fluetooth plugin.
version: 1.0.1
publish_to: 'none' 

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  esc_pos_gen: ^3.2.0
  flutter:
    sdk: flutter

  fluetooth_plus:
    path: ../
  image: ^3.1.0
  shared_preferences: 2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
