name: fluetooth_plus
description: Flutter library for sending bytes to Bluetooth devices.
version: 0.1.0
repository: https://github.com/robbysoerya/fluetooth_plus
issue_tracker: https://github.com/robbysoerya/fluetooth_plus/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  
  plugin:
    platforms:
      android:
        package: app.iandis.fluetooth
        pluginClass: FluetoothPlugin
      ios:
        pluginClass: FluetoothPlugin
